//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeeper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeKeeper.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Your Usual Activity.
        /// </summary>
        public static string AddCategoryPageName {
            get {
                return ResourceManager.GetString("AddCategoryPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AppBarButtonAddText {
            get {
                return ResourceManager.GetString("AppBarButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AppBarButtonDeleteText {
            get {
                return ResourceManager.GetString("AppBarButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string AppBarButtonStatisticsText {
            get {
                return ResourceManager.GetString("AppBarButtonStatisticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Keeper.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating TimeKeeper performance values..
        /// </summary>
        public static string BackgroundAgentDescription {
            get {
                return ResourceManager.GetString("BackgroundAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user..
        /// </summary>
        public static string BackgroundAgentsDisabled {
            get {
                return ResourceManager.GetString("BackgroundAgentsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string DeleteCategoryCaption {
            get {
                return ResourceManager.GetString("DeleteCategoryCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete activity &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteCategoryMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Activity.
        /// </summary>
        public static string DeleteCategoryPageName {
            get {
                return ResourceManager.GetString("DeleteCategoryPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string ImportantText {
            get {
                return ResourceManager.GetString("ImportantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Activity.
        /// </summary>
        public static string MainPageName {
            get {
                return ResourceManager.GetString("MainPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not important.
        /// </summary>
        public static string NotImportantText {
            get {
                return ResourceManager.GetString("NotImportantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not urgent.
        /// </summary>
        public static string NotUrgentText {
            get {
                return ResourceManager.GetString("NotUrgentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your perf: {0}%.
        /// </summary>
        public static string PerformanceShortText {
            get {
                return ResourceManager.GetString("PerformanceShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category for this activity relatively of your goals. Be objective!.
        /// </summary>
        public static string SelectCategoryText {
            get {
                return ResourceManager.GetString("SelectCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time: {0}.
        /// </summary>
        public static string StatCountedTimeText {
            get {
                return ResourceManager.GetString("StatCountedTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsPageName {
            get {
                return ResourceManager.GetString("StatisticsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Time: {0}.
        /// </summary>
        public static string StatUncountedTimeText {
            get {
                return ResourceManager.GetString("StatUncountedTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilized Time: {0}.
        /// </summary>
        public static string StatUtilizedTimeText {
            get {
                return ResourceManager.GetString("StatUtilizedTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string UrgentText {
            get {
                return ResourceManager.GetString("UrgentText", resourceCulture);
            }
        }
    }
}
