//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeKeeper.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeKeeper.Core.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&apos;CategorieList&apos;: [{&apos;Name&apos;: &apos;Working&apos;, &apos;Urgent&apos;: false, &apos;Important&apos;: true}, {&apos;Name&apos;: &apos;Learning&apos;, &apos;Urgent&apos;: false, &apos;Important&apos;: true}, {&apos;Name&apos;: &apos;Eating&apos;, &apos;Urgent&apos;: true, 
        ///&apos;Important&apos;: false}, {&apos;Name&apos;: &apos;Driving&apos;, &apos;Urgent&apos;: true, &apos;Important&apos;: false}, {&apos;Name&apos;: &apos;Sleeping&apos;, &apos;Urgent&apos;: true, &apos;Important&apos;: false}, {&apos;Name&apos;: &apos;TV&apos;, &apos;Urgent&apos;: false, &apos;Important&apos;: false}, {&apos;Name&apos;: &apos;Walking&apos;, &apos;Urgent&apos;: false, &apos;Important&apos;: true}, {&apos;Name&apos;: &apos;Talking&apos;, &apos;Urgent&apos;: false, &apos;Important&apos;: false}, {&apos;Name&apos;: &apos;Internet&apos;, &apos;Urgent&apos;: false, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultCategories {
            get {
                return ResourceManager.GetString("DefaultCategories", resourceCulture);
            }
        }
    }
}
